### ISSUE TITLE
Double slash in the path

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#620]
From the old ticket: https://github.com/Xtraball/Siberian416/issues/24

"@sl45sms: This line has Double slash in the path of plugman."

Like I have said before (in the previous ticket), double slash always here at this time (2019-05-29):
- https://github.com/Xtraball/Siberian/blob/master/bin/src/install.js#L15

**Comment by Slicit** [comment]
Fixed.
https://github.com/Xtraball/Siberian/blob/develop/bin/src/install.js#L15

**Comment by userdevel** [comment]
Thanks :)
Yes, I had added the link to the bad repository ^^

**Comment by Neustradamus** [comment]
@SiberianCMS @Slicit: Today, I have compared the code with old closed issues, a lot of closed issues but no solution, and for this issue, I confirm that it is not solved:
- https://github.com/Xtraball/Siberian/blob/master/bin/src/install.js#L15

I think that there are problems in your code, missing changements...

**Comment by SiberianCMS** [comment]
@Neustradamus just d a tiny pull request we will merge it asap, thanks.

**Comment by Neustradamus** [comment]
@SiberianCMS @Slicit: Thanks and there is https://github.com/Xtraball/Siberian/issues/703.
The problem is that all the code is really big, it can be separate in 2 parts.

**Comment by Neustradamus** [comment]
@SiberianCMS: It has been solved here (little days after my reminder): https://github.com/Xtraball/Siberian/commit/2d9f7faa83185123c4f9d41d9e6e6cc74c64a7a7#diff-91148397475888d85eb6c1891ece9de8
